# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=1)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
