# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200120_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calc',
            old_name='num1',
            new_name='n1',
        ),
        migrations.RenameField(
            model_name='calc',
            old_name='num2',
            new_name='n2',
        ),
    ]
