# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
